// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

models/echoes/5ton.mdl
models/echoes/barney_bshift.mdl
models/echoes/barney_civ.mdl
models/echoes/bradley.mdl
models/echoes/combat_suv_anim.mdl
models/echoes/construction.mdl
models/echoes/flyer.mdl
models/echoes/flyer_gibs.mdl
models/echoes/garg.mdl
models/echoes/gorepile.mdl
models/echoes/hassassin.mdl
models/echoes/hgrunt.mdl
models/echoes/hgrunt_opfor.mdl
models/echoes/islave.mdl
models/echoes/light.mdl
models/echoes/osprey.mdl
models/echoes/osprey_bodygibs.mdl
models/echoes/osprey_enginegibs.mdl
models/echoes/osprey_tailgibs.mdl
models/echoes/pcvvest.mdl
models/echoes/scientist.mdl
models/echoes/scientist_bshift.mdl
models/echoes/tree.mdl
models/echoes/truck_research.mdl
models/echoes/v_357.mdl
models/echoes/v_9mmar.mdl
models/echoes/v_9mmhandgun.mdl
models/echoes/v_crossbow.mdl
models/echoes/v_crowbar.mdl
models/echoes/v_egon.mdl
models/echoes/v_grenade.mdl
models/echoes/v_m16a2.mdl
models/echoes/v_medkit.mdl
models/echoes/v_rpg.mdl
models/echoes/v_satchel.mdl
models/echoes/v_satchel_radio.mdl
models/echoes/v_shotgun.mdl
models/echoes/v_squeak.mdl
models/echoes/v_tripmine.mdl
models/echoes/zombie.mdl
models/echoes/zombie_barney2.mdl
sound/barney/ba_endline.mp3
sound/echoes/agamemnon/ag_damn.ogg
sound/echoes/agamemnon/ag_headroll.ogg
sound/echoes/agamemnon/ag_meet0.ogg
sound/echoes/agamemnon/ag_meet1.ogg
sound/echoes/agamemnon/ag_meet2.ogg
sound/echoes/agamemnon/ag_meet3.ogg
sound/echoes/agamemnon/ag_meet4.ogg
sound/echoes/agamemnon/ag_meet5.ogg
sound/echoes/agamemnon/ag_meet6.ogg
sound/echoes/agamemnon/ag_meet7.ogg
sound/echoes/agamemnon/ag_paymess.ogg
sound/echoes/agamemnon/ag_tv1_0testing.ogg
sound/echoes/agamemnon/ag_tv1_1yesgood.ogg
sound/echoes/agamemnon/ag_tv1_2anywhere.ogg
sound/echoes/agamemnon/ag_tv4_0foundguard.ogg
sound/echoes/agamemnon/ag_tv4_1codes.ogg
sound/echoes/agamemnon/ag_tv4_2await.ogg
sound/echoes/agamemnon/ag_tv5wrong.ogg
sound/echoes/barney/_comma.ogg
sound/echoes/barney/ba_blocked.ogg
sound/echoes/barney/ba_goodshoot.ogg
sound/echoes/barney/ba_gundying.ogg
sound/echoes/barney/ba_ht07_04.ogg
sound/echoes/barney/ba_laugh01.ogg
sound/echoes/barney/ba_laugh02.ogg
sound/echoes/barney/ba_laugh03.ogg
sound/echoes/barney/ba_longnite.ogg
sound/echoes/barney/ba_movie.ogg
sound/echoes/barney/ba_protect.ogg
sound/echoes/barney/ba_safe1.ogg
sound/echoes/barney/ba_shit.ogg
sound/echoes/barney/ba_soldier.ogg
sound/echoes/barney/ba_spawn.ogg
sound/echoes/barney/c1a4_ba_octo2.ogg
sound/echoes/barney/goodteam.ogg
sound/echoes/barney/mil_nevermakeit.ogg
sound/echoes/barney/nocandoo.ogg
sound/echoes/barney/withoutme.ogg
sound/echoes/common/bodydrop3.ogg
sound/echoes/common/bodydrop4.ogg
sound/echoes/common/bodysplat.ogg
sound/echoes/common/npc_step1.ogg
sound/echoes/common/npc_step2.ogg
sound/echoes/common/npc_step3.ogg
sound/echoes/common/npc_step4.ogg
sound/echoes/debris/bustflesh1.ogg
sound/echoes/debris/bustflesh2.ogg
sound/echoes/debris/flesh1.ogg
sound/echoes/debris/flesh2.ogg
sound/echoes/debris/flesh3.ogg
sound/echoes/debris/flesh5.ogg
sound/echoes/debris/flesh6.ogg
sound/echoes/debris/flesh7.ogg
sound/echoes/echoes_materials.txt
sound/echoes/env/battle_loop1.ogg
sound/echoes/env/battle_loop2.ogg
sound/echoes/env/generator_alarm.ogg
sound/echoes/env/jet_flyby_quick.ogg
sound/echoes/env/osprey_takeoff.ogg
sound/echoes/env/vent.ogg
sound/echoes/flyer/flyer_appear.ogg
sound/echoes/flyer/flyer_die.ogg
sound/echoes/flyer/flyer_idle.ogg
sound/echoes/flyer/flyerbeam.ogg
sound/echoes/flyer/ospreycrash.ogg
sound/echoes/flyer/zapper_warmup2.ogg
sound/echoes/gman/gman_again.ogg
sound/echoes/gman/gman_belong.ogg
sound/echoes/gman/gman_comebacknow.ogg
sound/echoes/gman/gman_cutoff.ogg
sound/echoes/gman/gman_getbackhere.ogg
sound/echoes/gman/gman_huff.ogg
sound/echoes/gman/gman_laugh01.ogg
sound/echoes/gman/gman_meetagain.ogg
sound/echoes/gman/gman_nicetohaveyou.ogg
sound/echoes/gman/gman_notforlong.ogg
sound/echoes/gman/gman_notthistime.ogg
sound/echoes/gman/gman_ohno.ogg
sound/echoes/gman/gman_oldtimes.ogg
sound/echoes/gman/gman_payattention.ogg
sound/echoes/gman/gman_prepare.ogg
sound/echoes/gman/gman_ratherbusy.ogg
sound/echoes/gman/gman_scare.ogg
sound/echoes/gman/gman_see.ogg
sound/echoes/gman/gman_snarl01.ogg
sound/echoes/gman/gman_snarl02.ogg
sound/echoes/gman/gman_snarl03.ogg
sound/echoes/gman/gman_thatsallfornow.ogg
sound/echoes/gman/gman_thatwillbeall.ogg
sound/echoes/gman/gman_wellsh.ogg
sound/echoes/gman/gman_wellsh2.ogg
sound/echoes/items/9mmclip1.ogg
sound/echoes/items/9mmclip2.ogg
sound/echoes/items/clipinsert1.ogg
sound/echoes/items/cliprelease1.ogg
sound/echoes/items/flashlight1.ogg
sound/echoes/items/gunpickup2.ogg
sound/echoes/items/weapondrop1.ogg
sound/echoes/media/Half-Life12.ogg
sound/echoes/media/Half-Life14.ogg
sound/echoes/military/exitdoorpanel.ogg
sound/echoes/military/major_mortar.ogg
sound/echoes/military/mil_hold.ogg
sound/echoes/military/mil_rocket1.ogg
sound/echoes/military/mil_suppress.ogg
sound/echoes/military/mil_sweep.ogg
sound/echoes/military/mil_tank1.ogg
sound/echoes/military/mil_tank2.ogg
sound/echoes/military/mil_tank3.ogg
sound/echoes/military/mil_targetmortar.ogg
sound/echoes/military/mortar_activate.ogg
sound/echoes/military/osprey_shit.ogg
sound/echoes/outtro/portal1.ogg
sound/echoes/outtro/portal2.ogg
sound/echoes/outtro/portal3.ogg
sound/echoes/outtro/portal4.ogg
sound/echoes/player/sprayer.ogg
sound/echoes/scientist/_comma.ogg
sound/echoes/scientist/breakthings.ogg
sound/echoes/scientist/d01_sci10_interesting.ogg
sound/echoes/scientist/d01_sci14_right.ogg
sound/echoes/scientist/drunk.ogg
sound/echoes/scientist/fork_impossible.ogg
sound/echoes/scientist/fork_phd.ogg
sound/echoes/scientist/fork_theoretically.ogg
sound/echoes/scientist/nil.ogg
sound/echoes/scientist/nogrant.ogg
sound/echoes/scientist/okgetout.ogg
sound/echoes/scientist/sc_holdyourself.ogg
sound/echoes/scientist/sc_please.ogg
sound/echoes/scientist/sci_fear8.ogg
sound/echoes/scientist/sneeze.ogg
sound/echoes/scientist/thankgod.ogg
sound/echoes/scientist/tramangry.ogg
sound/echoes/scientist/tramcough.ogg
sound/echoes/weapons/cbar_hit1.ogg
sound/echoes/weapons/cbar_hit2.ogg
sound/echoes/weapons/cbar_hitbod1.ogg
sound/echoes/weapons/cbar_hitbod2.ogg
sound/echoes/weapons/cbar_hitbod3.ogg
sound/echoes/weapons/cbar_miss1.ogg
sound/echoes/weapons/rocketfire1.ogg
sound/scientist/excellentteam.mp3
sprites/echoes/muzzleflash2.spr
sprites/echoes/newfire1.spr
sprites/echoes/newfire2.spr
sprites/echoes/newfire3.spr
sprites/echoes/redglow.spr
sprites/echoes/spotlight.spr
