// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/player/DGF_p_spetsnaz/DGF_p_spetsnaz.bmp
models/player/DGF_p_spetsnaz/DGF_p_spetsnaz.mdl
models/sc_russian/128_fuse_set02.mdl
models/sc_russian/barrel_metal.mdl
models/sc_russian/burer.mdl
models/sc_russian/capacity_cod4_01.mdl
models/sc_russian/cars/dgf_mi6arm_fly.mdl
models/sc_russian/cc_chair_01.mdl
models/sc_russian/cc_desk02.mdl
models/sc_russian/cc_oscilator.mdl
models/sc_russian/chair_stool01a.mdl
models/sc_russian/cistern_szp_001.mdl
models/sc_russian/controller.mdl
models/sc_russian/dgf_chimera.mdl
models/sc_russian/dgf_flies.mdl
models/sc_russian/dgf_flies_big.mdl
models/sc_russian/dgf_flies_proj.mdl
models/sc_russian/dgf_hazmat.mdl
models/sc_russian/dgf_hind.mdl
models/sc_russian/dgf_hwgrunt.mdl
models/sc_russian/dgf_mosquito.mdl
models/sc_russian/dgf_pseudodog_grey.mdl
models/sc_russian/dgf_pseudogiant.mdl
models/sc_russian/dgf_rat.mdl
models/sc_russian/dgf_rsoldier.mdl
models/sc_russian/dgf_scientist.mdl
models/sc_russian/dgf_snork.mdl
models/sc_russian/dgf_tushkano.mdl
models/sc_russian/dgf_zombie.mdl
models/sc_russian/dgf_zombie_soldier.mdl
models/sc_russian/dgf_zombie_soldier_up.mdl
models/sc_russian/electricalbox01.mdl
models/sc_russian/f3_shkaf.mdl
models/sc_russian/fence.mdl
models/sc_russian/firepipe.mdl
models/sc_russian/fork.mdl
models/sc_russian/geo_motor3.mdl
models/sc_russian/gonome.mdl
models/sc_russian/gore/cadaver-open.mdl
models/sc_russian/gore/corpse9.mdl
models/sc_russian/gore/geo_deadgirl.mdl
models/sc_russian/gore/geo_katalka_deadman.mdl
models/sc_russian/gore/geo_stol_trup.mdl
models/sc_russian/gore/maniak_gmurikvmeshke.mdl
models/sc_russian/gore/researcher_arm.mdl
models/sc_russian/gurulo.mdl
models/sc_russian/hgrunt_torch.mdl
models/sc_russian/kran1.mdl
models/sc_russian/lamp02.mdl
models/sc_russian/lamp_hanging-industrial.mdl
models/sc_russian/light_industrial3.mdl
models/sc_russian/lightspot.mdl
models/sc_russian/medical/armbox.mdl
models/sc_russian/medical/cc_drugcab_01.mdl
models/sc_russian/medical/cc_lab_thermostat_02.mdl
models/sc_russian/medical/cc_lab_tubes.mdl
models/sc_russian/medical/curtain.mdl
models/sc_russian/medical/geo_mufel.mdl
models/sc_russian/medical/krankenbett.mdl
models/sc_russian/medical/operating_table_soiled.mdl
models/sc_russian/medical/p2_comp_1980.mdl
models/sc_russian/medical/p2_control_desk.mdl
models/sc_russian/medical/pen2_microscope.mdl
models/sc_russian/medical/showers.mdl
models/sc_russian/medical/sterilizer.mdl
models/sc_russian/medical/surgical_tray.mdl
models/sc_russian/mtl_machine.mdl
models/sc_russian/mtl_machine2.mdl
models/sc_russian/npsociety/pack_bierres1.mdl
models/sc_russian/p_357.mdl
models/sc_russian/p_9mmar.mdl
models/sc_russian/p_9mmhandgun.mdl
models/sc_russian/p_crowbar.mdl
models/sc_russian/p_desert_eagle.mdl
models/sc_russian/p_grenade.mdl
models/sc_russian/p_m16.mdl
models/sc_russian/p_medkit.mdl
models/sc_russian/p_rpg.mdl
models/sc_russian/p_rpg_r.mdl
models/sc_russian/p_saw.mdl
models/sc_russian/p_shotgun.mdl
models/sc_russian/pkm_sentry.mdl
models/sc_russian/pkm_sentryt.mdl
models/sc_russian/s_shelf.mdl
models/sc_russian/tok_stanok.mdl
models/sc_russian/v_357.mdl
models/sc_russian/v_9mmar.mdl
models/sc_russian/v_9mmhandgun.mdl
models/sc_russian/v_crowbar.mdl
models/sc_russian/v_desert_eagle.mdl
models/sc_russian/v_grenade.mdl
models/sc_russian/v_m16a2.mdl
models/sc_russian/v_medkit.mdl
models/sc_russian/v_rpg.mdl
models/sc_russian/v_saw.mdl
models/sc_russian/v_shotgun.mdl
models/sc_russian/valise_bact.mdl
models/sc_russian/vent_roof2a.mdl
models/sc_russian/ventilation_shhc_001.mdl
models/sc_russian/w_9mmar.mdl
models/sc_russian/w_9mmarclip.mdl
models/sc_russian/w_9mmhandgun.mdl
models/sc_russian/w_argrenade.mdl
models/sc_russian/w_crowbar.mdl
models/sc_russian/w_crowbart.mdl
models/sc_russian/w_desert_eagle.mdl
models/sc_russian/w_grenade.mdl
models/sc_russian/w_grenadet.mdl
models/sc_russian/w_m16.mdl
models/sc_russian/w_pmedkit.mdl
models/sc_russian/w_rpg.mdl
models/sc_russian/w_rpgammo.mdl
models/sc_russian/w_saw.mdl
models/sc_russian/w_saw_clip.mdl
models/sc_russian/w_shotbox.mdl
models/sc_russian/w_shotgun.mdl
models/sc_russian/water_container.mdl
models/sc_russian/zps_warehouse_shelfes.mdl
models/sc_russian/zps_warehouse_shelfes2.mdl
sound/ambience/elev_creak3.wav
sound/russian_sounds/bloodsucker/hit_0.ogg
sound/russian_sounds/bloodsucker/hit_1.ogg
sound/russian_sounds/bloodsucker/hit_2.ogg
sound/russian_sounds/bloodsucker/hit_3.ogg
sound/russian_sounds/bloodsucker/idle_0.ogg
sound/russian_sounds/bloodsucker/idle_1.ogg
sound/russian_sounds/bloodsucker/idle_2.ogg
sound/russian_sounds/bloodsucker/sucker_breath_0.ogg
sound/russian_sounds/bloodsucker/sucker_growl_2.ogg
sound/russian_sounds/bloodsucker/sucker_growl_3.ogg
sound/russian_sounds/bloodsucker/sucker_growl_4.ogg
sound/russian_sounds/bloodsucker/vampire_grasp.ogg
sound/russian_sounds/bloodsucker/vampire_sucking.ogg
sound/russian_sounds/burer/burer_attack_0.ogg
sound/russian_sounds/burer/burer_attacking_0.ogg
sound/russian_sounds/burer/burer_gravi_attack_0.ogg
sound/russian_sounds/burer/burer_nosound.ogg
sound/russian_sounds/burer/burer_telekinetic_0.ogg
sound/russian_sounds/buzzer_fan1.wav
sound/russian_sounds/buzzer_highvol.wav
sound/russian_sounds/buzzer_machine1.wav
sound/russian_sounds/buzzer_machine5.wav
sound/russian_sounds/buzzer_p_trevoga.wav
sound/russian_sounds/buzzer_shumvzdanii.wav
sound/russian_sounds/controller/final_hit.ogg
sound/russian_sounds/controller/first_hit.ogg
sound/russian_sounds/controller/tube_prepare.ogg
sound/russian_sounds/giant/giant_aggressive_0.ogg
sound/russian_sounds/giant/giant_aggressive_1.ogg
sound/russian_sounds/giant/giant_breath_0.ogg
sound/russian_sounds/giant/giant_breath_1.ogg
sound/russian_sounds/giant/giant_breath_2.ogg
sound/russian_sounds/giant/giant_death_0.ogg
sound/russian_sounds/giant/giant_death_1.ogg
sound/russian_sounds/giant/giant_hurt_0.ogg
sound/russian_sounds/giant/giant_hurt_1.ogg
sound/russian_sounds/giant/giant_hurt_2.ogg
sound/russian_sounds/hangar_wind1.wav
sound/russian_sounds/hind/helicopter2.ogg
sound/russian_sounds/music/amb17_r.ogg
sound/russian_sounds/music/dgf_action03.wav
sound/russian_sounds/music/dgf_ambiance02.wav
sound/russian_sounds/music/dgf_ambiance04.wav
sound/russian_sounds/music/dgf_ambiance05.wav
sound/russian_sounds/pseudodog/pdog_aggression_0.ogg
sound/russian_sounds/pseudodog/pdog_aggression_1.ogg
sound/russian_sounds/pseudodog/pdog_attack_0.ogg
sound/russian_sounds/pseudodog/pdog_attack_1.ogg
sound/russian_sounds/pseudodog/pdog_attack_2.ogg
sound/russian_sounds/pseudodog/pdog_attack_3.ogg
sound/russian_sounds/pseudodog/pdog_death_0.ogg
sound/russian_sounds/pseudodog/pdog_death_1.ogg
sound/russian_sounds/pseudodog/pdog_hurt_0.ogg
sound/russian_sounds/pseudodog/pdog_hurt_1.ogg
sound/russian_sounds/pseudodog/pdog_nosound.ogg
sound/russian_sounds/pseudodog/pdog_threaten_0.ogg
sound/russian_sounds/pseudodog/pdog_threaten_1.ogg
sound/russian_sounds/pseudodog/pdog_threaten_2.ogg
sound/russian_sounds/snork/snork_attack_0.ogg
sound/russian_sounds/snork/snork_attack_1.ogg
sound/russian_sounds/snork/snork_attack_hit_0.ogg
sound/russian_sounds/snork/snork_attack_hit_1.ogg
sound/russian_sounds/snork/snork_idle_0.ogg
sound/russian_sounds/snork/snork_idle_1.ogg
sound/russian_sounds/snork/snork_idle_2.ogg
sound/russian_sounds/test2_shoot.ogg
sound/russian_sounds/tushkano/attack_0.ogg
sound/russian_sounds/tushkano/attack_1.ogg
sound/russian_sounds/tushkano/nosound.ogg
sound/russian_sounds/tushkano/pain_0.ogg
sound/russian_sounds/tushkano/pain_1.ogg
sound/russian_sounds/tushkano/threaten_0.ogg
sound/russian_sounds/tushkano/threaten_1.ogg
sound/russian_sounds/tushkano/threaten_2.ogg
sound/russian_sounds/veh_seaknight_idle_v5.wav
sound/russian_sounds/zombie/zombie_attack_1.ogg
sound/russian_sounds/zombie/zombie_attack_2.ogg
sound/russian_sounds/zombie/zombie_eat_0.ogg
sound/russian_sounds/zombie/zombie_eat_1.ogg
sound/russian_sounds/zombie/zombie_eat_2.ogg
sound/russian_sounds/zombie/zombie_idle_1.ogg
sound/russian_sounds/zombie/zombie_idle_2.ogg
sound/russian_sounds/zombie/zombie_idle_3.ogg
sound/russian_sounds/zombie/zombie_idle_4.ogg
sound/russian_sounds/zombie/zombie_miss.ogg
sound/russian_sounds/zombie/zombie_pain1.ogg
sound/russian_sounds/zombie/zombie_pain2.ogg
sound/russian_sounds/zufire.wav
sound/weapons/629_shells_land.wav
sound/weapons/ak-101/gp25_reload_stalker.wav
sound/weapons/grenade_throw.wav
sound/weapons/pinpull.wav
sound/weapons/pm_draw.wav
sound/weapons/pm_reload1.wav
sound/weapons/pm_reload2.wav
sound/weapons/pm_reload3.wav
sound/weapons/pm_reload4.wav
sound/weapons/pm_reload5.wav
sound/weapons/revolvers_bulletsin.wav
sound/weapons/revolvers_rod.wav
sound/weapons/revolvers_wheelin.wav
sound/weapons/revolvers_wheelout.wav
sound/weapons/rpgreload.wav
sound/weapons/stalker/Boltpull.wav
sound/weapons/stalker/Magin.wav
sound/weapons/stalker/Magout.wav
sprites/russian_spr/dgf_itemglint.spr
